# Generated by Django 5.1.6 on 2025-02-24 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('relationship_app', '0003_adminprofile_librarianprofile_memberprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Librarian', 'Librarian'), ('Member', 'Member')], default='Member', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='librarianprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='LibrarianProfile',
        ),
        migrations.DeleteModel(
            name='MemberProfile',
        ),
    ]
