# Generated by Django 5.1.6 on 2025-02-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_UserProfile_remove_librarianUserProfile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
